apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80 # Or a port you want to expose externally
      targetPort: 8080 # Or the containerPort
  type: LoadBalancer # Use ClusterIP for internal access only, LoadBalancer for external (if supported by your Kind setup)