apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: sanjnaaax5/inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083 # Or the port your Inventory Service runs on
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
          # Add other environment variables as needed