apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: sanjnaax5/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084 # Or the port your Notification Service runs on
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
          # Add other environment variables as needed